import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dae2fd",
        "surface-tint": "#d2bbff",
        "inverse-primary": "#732ee4",
        "inverse-on-surface": "#283044",
        "primary-fixed": "#eaddff",
        surface: "#0b1326",
        "on-tertiary": "#3a3000",
        secondary: "#ddfcff",
        "surface-container-low": "#131b2e",
        "secondary-fixed": "#74f5ff",
        "on-surface": "#dae2fd",
        background: "#0b1326",
        "on-secondary-container": "#006a70",
        "on-tertiary-container": "#4c3e00",
        "surface-container-lowest": "#060e20",
        "tertiary-fixed-dim": "#e9c400",
        "tertiary-container": "#c9a900",
        "error-container": "#93000a",
        "on-secondary-fixed": "#002022",
        "surface-container": "#171f33",
        "on-secondary": "#00363a",
        "surface-variant": "#2d3449",
        "primary-container": "#7c3aed",
        "tertiary-fixed": "#ffe16d",
        "on-tertiary-fixed-variant": "#544600",
        "on-tertiary-fixed": "#221b00",
        "surface-dim": "#0b1326",
        "secondary-fixed-dim": "#00dbe7",
        "on-primary": "#3f008e",
        "on-primary-fixed": "#25005a",
        "secondary-container": "#00f1fe",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#ede0ff",
        outline: "#958da1",
        "on-secondary-fixed-variant": "#004f54",
        "on-surface-variant": "#ccc3d8",
        "outline-variant": "#4a4455",
        "surface-bright": "#31394d",
        "primary-fixed-dim": "#d2bbff",
        error: "#ffb4ab",
        "surface-container-high": "#222a3d",
        "on-background": "#dae2fd",
        "surface-container-highest": "#2d3449",
        "on-error": "#690005",
        primary: "#d2bbff",
        tertiary: "#e9c400",
        "on-primary-fixed-variant": "#5a00c6",
        "valo-red": "#ff4655",
        "valo-dark": "#0f1923",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        "spacing-lg": "40px",
        "spacing-xl": "64px",
        "margin-desktop": "48px",
        md: "24px",
        "margin-mobile": "16px",
        sm: "12px",
        base: "8px",
        gutter: "24px",
      },
      fontFamily: {
        display: ["Sora", "sans-serif"],
        heading: ["Sora", "sans-serif"],
        body: ["Hanken Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-sm": ["36px", { lineHeight: "1.2", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.03em", fontWeight: "700" }],
      },
      keyframes: {
        "pulse-red": {
          "0%": { boxShadow: "0 0 0 0 rgba(255, 70, 85, 0.7)" },
          "70%": { boxShadow: "0 0 0 10px rgba(255, 70, 85, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(255, 70, 85, 0)" },
        },
        float: {
          "0%": { transform: "translateY(0) scale(1)", opacity: "0" },
          "50%": { opacity: "0.5" },
          "100%": { transform: "translateY(-100px) scale(1.5)", opacity: "0" },
        },
        "slide-in": {
          "0%": { transform: "translateX(-10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "pulse-red": "pulse-red 1s infinite",
        float: "float 3s infinite linear",
        "slide-in": "slide-in 0.3s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        shimmer: "shimmer 2s infinite linear",
      },
    },
  },
  plugins: [],
};

export default config;
