/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#0b1326",
        background: "#0b1326",
        "on-surface": "#dae2fd",
        "on-background": "#dae2fd",
        primary: "#d2bbff",
        "primary-container": "#7c3aed",
        "on-primary": "#3f008e",
        "on-primary-container": "#ede0ff",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-fixed": "#25005a",
        secondary: "#ddfcff",
        "secondary-container": "#00f1fe",
        "on-secondary": "#00363a",
        "on-secondary-container": "#006a70",
        "secondary-fixed": "#74f5ff",
        "secondary-fixed-dim": "#00dbe7",
        tertiary: "#e9c400",
        "tertiary-container": "#c9a900",
        "tertiary-fixed": "#ffe16d",
        "tertiary-fixed-dim": "#e9c400",
        "on-tertiary": "#3a3000",
        "on-tertiary-container": "#4c3e00",
        "on-tertiary-fixed": "#221b00",
        "on-tertiary-fixed-variant": "#544600",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        outline: "#958da1",
        "outline-variant": "#4a4455",
        "surface-variant": "#2d3449",
        "on-surface-variant": "#ccc3d8",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-tint": "#d2bbff",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "inverse-primary": "#732ee4",
        "valo-red": "#ff4655",
        "valo-dark": "#0f1923",
      },
    },
  },
  plugins: [],
};